name: dart_sm_new
description: 基于Dart语言实现的国密SM2、SM3、SM4算法。
version: 0.1.8
homepage: https://github.com/idcpj/dart_sm_new.git

environment:
  sdk: '>=2.18.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
